name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  APP_ENV: dev
  APP_HOST: 0.0.0.0
  APP_PORT: 3000
  DB_HOST: localhost
  DB_USER: postgres
  DB_PASSWORD: thisisasamplepassword
  DB_NAME: fiberdb
  DB_PORT: 5432
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_PASSWORD: thisisaredispassword
  REDIS_DB: 0
  REDIS_PREFIX: app_

jobs:
  GoFiber:
    runs-on: ubuntu-latest

    services:
      postgresdb:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: thisisasamplepassword
          POSTGRES_DB: fiberdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 20s
          --health-retries 10
          
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          REDIS_PASSWORD: thisisaredispassword

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -U postgres -d fiberdb; do
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Install dependencies
        run: go mod tidy

      - name: Build Go application
        run: CGO_ENABLED=0 GOOS=linux go build src/main.go
        env:
          APP_ENV: ${{ env.APP_ENV }}
          APP_HOST: ${{ env.APP_HOST }}
          APP_PORT: ${{ env.APP_PORT }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_PORT: ${{ env.DB_PORT }}
          REDIS_HOST: ${{ env.REDIS_HOST }}
          REDIS_PORT: ${{ env.REDIS_PORT }}
          REDIS_PASSWORD: ${{ env.REDIS_PASSWORD }}
          REDIS_DB: ${{ env.REDIS_DB }}
          REDIS_PREFIX: ${{ env.REDIS_PREFIX }}
